name: AutoRelease

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: zip -r release.zip pack.mcmeta assets

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(gh release view --json tagName -q ".tagName")
          [[ $VERSION =~ [0-9]*$ ]]
          INDEX=$BASH_REMATCH
          [[ $VERSION =~ (.*)$INDEX ]]
          VERSION="${BASH_REMATCH[1]}$(( $INDEX + 1 ))"
          gh release create $VERSION release.zip
